# Generated by Django 2.1.5 on 2019-06-16 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_titre', models.CharField(max_length=100, verbose_name="Titre de l'article")),
                ('art_auteur', models.CharField(max_length=42, verbose_name="Auteur de l'article")),
                ('art_contenu', models.TextField(null=True, verbose_name="Contenu de l'article")),
                ('art_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('art_masquer', models.BooleanField(default=True, verbose_name='Article masqué')),
                ('art_ima_presentation', models.ImageField(null=True, upload_to='photos/', verbose_name='Image presentation')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['art_date'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_nom', models.CharField(default='empty', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_auteur', models.CharField(max_length=42, verbose_name='Auteur du commentaire')),
                ('com_art_titre', models.CharField(max_length=100, verbose_name="Titre de l'article associé au commentaire")),
                ('com_art_id', models.IntegerField(verbose_name="Id de l'article associé au commentaire")),
                ('com_contenu', models.TextField(null=True, verbose_name='Contenu du commentaire')),
                ('com_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'verbose_name': "Commentaire d'article",
                'ordering': ['-com_date'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ima_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('ima_masquer', models.BooleanField(default=True, verbose_name='Image masquée')),
                ('ima_image', models.ImageField(null=True, upload_to='photos/', verbose_name='Image')),
                ('ima_description', models.CharField(max_length=100, verbose_name="description de l'image")),
                ('ima_art_titre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.Article', verbose_name="Titre de l'article associé à l'image")),
            ],
            options={
                'verbose_name': 'images',
                'ordering': ['-ima_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_titre', models.CharField(max_length=30, verbose_name='Titre de la video')),
                ('vid_desc', models.CharField(max_length=200, verbose_name='Description de la video')),
                ('vid_link', models.CharField(max_length=100, verbose_name='Lien de la video')),
                ('vid_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la video')),
            ],
            options={
                'verbose_name': 'video',
                'ordering': ['vid_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='art_categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.Categorie', verbose_name="Catégorie de l'article"),
        ),
    ]
