# Generated by Django 2.1.5 on 2019-11-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20191103_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='art_categorie',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_titre',
            field=models.CharField(max_length=100, verbose_name="Titre de l'article"),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
